
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pham-anh-Hub/Microservice-configuration
          default-label: main
server:
  port: 8888
